#!/bin/bash

# Este esta expresado en el periodo

xmin=-0.5
xmax=3.5
ymin=0
ymax=6000

gnuplot << EOF

set terminal jpeg medium
set output "emj_messageSize.jpg"

set xlabel 'message size (Bytes)'
set ylabel 'average maximum jitter (ms)'

set key top left
set xtics ("512"0,"1024"1,"3072"2,"6144"3)

#set title "variación del retardo en base al tamaño del mensaje"
#set title "jitter variation based on the message size"

plot [$xmin:$xmax] [$ymin:$ymax] "10.txt" u 3 title "10 ms" w linespoints, \
				"100.txt" u 3 title "100 ms" w linespoints, \
				"500.txt" u 3 title "500 ms" w linespoints, \
				"1000.txt" u 3 title "1000 ms" w linespoints

set output
EOF
